-- INSERT INTO students(
--     id,
--   email,
--   first_name,
--   last_name,
--   parent_phone,
--   zipcode,
--   password,
--   sat_score,
--   act_score,
--   enrollment,
--   school_type ) VALUES (0, 'test-email@test.com', 'test-first_name', 'test-last_name', '3476640645', '93117', 'test-password', 1440 , 31, 350, 'test-school_type')